<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="MSI" failures="2" tests="8" name="retry Test" time="0.052" errors="0" timestamp="2021-09-13T16:27:40 IST">
  <testcase classname="RetryLogicUsingTestNG.TestNGRetry.RetryTest" name="Test1" time="0.009">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase classname="RetryLogicUsingTestNG.TestNGRetry.RetryTest" name="Test1" time="0.001">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase classname="RetryLogicUsingTestNG.TestNGRetry.RetryTest" name="Test1" time="0.0">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase classname="RetryLogicUsingTestNG.TestNGRetry.RetryTest" name="Test1" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at RetryLogicUsingTestNG.TestNGRetry.RetryTest.Test1(RetryTest.java:14)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- Test1 -->
  <testcase classname="RetryLogicUsingTestNG.TestNGRetry.RetryTest" name="Test2" time="0.0">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase classname="RetryLogicUsingTestNG.TestNGRetry.RetryTest" name="Test2" time="0.001">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase classname="RetryLogicUsingTestNG.TestNGRetry.RetryTest" name="Test2" time="0.001">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase classname="RetryLogicUsingTestNG.TestNGRetry.RetryTest" name="Test2" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at RetryLogicUsingTestNG.TestNGRetry.RetryTest.Test2(RetryTest.java:20)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- Test2 -->
</testsuite> <!-- retry Test -->
